--------------------------------------------------------
--  File creato - mercoledì-dicembre-01-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence S_ID_AREA
--------------------------------------------------------

   CREATE SEQUENCE  "ORION3G"."S_ID_AREA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence S_ID_CANTIERI
--------------------------------------------------------

   CREATE SEQUENCE  "ORION3G"."S_ID_CANTIERI"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 101 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence S_ID_LAVORATORE
--------------------------------------------------------

   CREATE SEQUENCE  "ORION3G"."S_ID_LAVORATORE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 101 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence S_ID_SENSORE
--------------------------------------------------------

   CREATE SEQUENCE  "ORION3G"."S_ID_SENSORE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 101 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table AREA
--------------------------------------------------------

  CREATE TABLE "ORION3G"."AREA" 
   (	"IDAREA" NUMBER(*,0), 
	"NOME" VARCHAR2(200 BYTE), 
	"IDLAV" NUMBER(*,0), 
	"IDCANT" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CANTIERE
--------------------------------------------------------

  CREATE TABLE "ORION3G"."CANTIERE" 
   (	"IDCANTIERE" NUMBER(*,0), 
	"NOME" VARCHAR2(200 BYTE), 
	"DESCRIZIONE" VARCHAR2(400 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CREDENZIALI
--------------------------------------------------------

  CREATE TABLE "ORION3G"."CREDENZIALI" 
   (	"UTENTE" VARCHAR2(200 BYTE), 
	"PASSWORD" VARCHAR2(200 BYTE), 
	"IDLAV" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DATISENSORE
--------------------------------------------------------

  CREATE TABLE "ORION3G"."DATISENSORE" 
   (	"DATORUMORE" FLOAT(20), 
	"DATOGAS" FLOAT(20), 
	"DATAG" DATE, 
	"ALLARME" NUMBER(1,0) DEFAULT 0, 
	"IDSENS" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LAVORATORE
--------------------------------------------------------

  CREATE TABLE "ORION3G"."LAVORATORE" 
   (	"IDLAV" NUMBER(*,0), 
	"NOME" VARCHAR2(200 BYTE), 
	"COGNOME" VARCHAR2(200 BYTE), 
	"DATAN" DATE, 
	"TIPOLAV" VARCHAR2(200 BYTE), 
	"IDCANT" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SENSORE
--------------------------------------------------------

  CREATE TABLE "ORION3G"."SENSORE" 
   (	"IDSENSORE" NUMBER(*,0), 
	"IDLAV" NUMBER(*,0), 
	"IDAREA" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for View VIEW_CANTIERE_AREA
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ORION3G"."VIEW_CANTIERE_AREA" ("NOME_CANTIERE", "IDCANTIERE", "NOME_AREA", "ID_AREA") AS 
  SELECT cantiere.nome AS NOME_CANTIERE, cantiere.idcantiere AS IDCANTIERE, area.nome AS NOME_AREA, area.idarea AS ID_AREA FROM area join cantiere ON AREA.IDCANT=CANTIERE.IDCANTIERE
;
--------------------------------------------------------
--  DDL for View VIEW_CANTIERE_AREA_SENSORE
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ORION3G"."VIEW_CANTIERE_AREA_SENSORE" ("NOME_CANTIERE", "ID_CANTIERE", "NOME_AREA", "ID_AREA", "DATO_RUMORE", "DATO_GAS") AS 
  SELECT cantiere.nome AS NOME_CANTIERE, cantiere.idcantiere AS ID_CANTIERE, area.nome AS NOME_AREA, area.idarea AS ID_AREA, sensore.datorumore AS DATO_RUMORE, 
sensore.datogas AS DATO_GAS FROM area join cantiere ON AREA.IDCANT=CANTIERE.IDCANTIERE JOIN sensore ON AREA.IDAREA=SENSORE.IDAREA
;
--------------------------------------------------------
--  DDL for View VIEW_CANTIERE_LAVORATORI
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ORION3G"."VIEW_CANTIERE_LAVORATORI" ("NOME_CANTIERE", "ID_CANTIERE", "ID_LAVORATORE", "NOME_LAVORATORE", "COGNOME_LAVORATORE", "TIPO_LAVORATORE") AS 
  SELECT cantiere.nome AS NOME_CANTIERE, cantiere.idcantiere AS ID_CANTIERE, lavoratore.idlav AS ID_LAVORATORE, lavoratore.nome AS NOME_LAVORATORE, lavoratore.cognome AS COGNOME_LAVORATORE, lavoratore.tipolav AS TIPO_LAVORATORE 
FROM cantiere join lavoratore ON CANTIERE.IDCANTIERE=lavoratore.idcant
;
--------------------------------------------------------
--  DDL for View VIEW_TIPO_LAV
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ORION3G"."VIEW_TIPO_LAV" ("TIPOLAV", "IDLAV") AS 
  select lavoratore.tipolav, lavoratore.idlav from credenziali join lavoratore ON credenziali.idlav=lavoratore.idlav
;
REM INSERTING into ORION3G.AREA
SET DEFINE OFF;
REM INSERTING into ORION3G.CANTIERE
SET DEFINE OFF;
Insert into ORION3G.CANTIERE (IDCANTIERE,NOME,DESCRIZIONE) values ('81','cantiere1','cantiere di prova');
REM INSERTING into ORION3G.CREDENZIALI
SET DEFINE OFF;
Insert into ORION3G.CREDENZIALI (UTENTE,PASSWORD,IDLAV) values ('mel01','1234','87');
REM INSERTING into ORION3G.DATISENSORE
SET DEFINE OFF;
REM INSERTING into ORION3G.LAVORATORE
SET DEFINE OFF;
Insert into ORION3G.LAVORATORE (IDLAV,NOME,COGNOME,DATAN,TIPOLAV,IDCANT) values ('84','Mario','Rossi',to_date('01-GEN-70','DD-MON-RR'),'OPERAIO SEMPLICE','81');
Insert into ORION3G.LAVORATORE (IDLAV,NOME,COGNOME,DATAN,TIPOLAV,IDCANT) values ('85','Luca','Verde',to_date('08-OTT-70','DD-MON-RR'),'CAPOC','81');
Insert into ORION3G.LAVORATORE (IDLAV,NOME,COGNOME,DATAN,TIPOLAV,IDCANT) values ('87','Agata','Gianni',to_date('08-OTT-70','DD-MON-RR'),'AMMINISTRATORE','81');
REM INSERTING into ORION3G.SENSORE
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index LAVORATORE_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "ORION3G"."LAVORATORE_UK1" ON "ORION3G"."LAVORATORE" ("NOME", "COGNOME", "DATAN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_AREA
--------------------------------------------------------

  CREATE UNIQUE INDEX "ORION3G"."PK_AREA" ON "ORION3G"."AREA" ("IDAREA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_CANTIERE
--------------------------------------------------------

  CREATE UNIQUE INDEX "ORION3G"."PK_CANTIERE" ON "ORION3G"."CANTIERE" ("IDCANTIERE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_CREDENZIALI
--------------------------------------------------------

  CREATE UNIQUE INDEX "ORION3G"."PK_CREDENZIALI" ON "ORION3G"."CREDENZIALI" ("UTENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_LAVORATORE
--------------------------------------------------------

  CREATE UNIQUE INDEX "ORION3G"."PK_LAVORATORE" ON "ORION3G"."LAVORATORE" ("IDLAV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_SENSORE
--------------------------------------------------------

  CREATE UNIQUE INDEX "ORION3G"."PK_SENSORE" ON "ORION3G"."SENSORE" ("IDSENSORE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger S_ID_SENSORE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ORION3G"."S_ID_SENSORE" 
BEFORE INSERT ON SENSORE
FOR EACH ROW
BEGIN
    :new.IDSENSORE:= S_ID_SENSORE.nextval;
END;


/
ALTER TRIGGER "ORION3G"."S_ID_SENSORE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_ID_AREA
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ORION3G"."T_ID_AREA" 
BEFORE INSERT ON AREA
FOR EACH ROW
BEGIN
    :new.IDAREA:= S_ID_AREA.nextval;
END;


/
ALTER TRIGGER "ORION3G"."T_ID_AREA" ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_ID_CANTIERI
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ORION3G"."T_ID_CANTIERI" 
BEFORE INSERT ON CANTIERE
FOR EACH ROW
BEGIN
    :new.IDCANTIERE:= S_ID_CANTIERI.nextval;
END;


/
ALTER TRIGGER "ORION3G"."T_ID_CANTIERI" ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_ID_LAVORATORE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ORION3G"."T_ID_LAVORATORE" 
BEFORE INSERT ON LAVORATORE
FOR EACH ROW
BEGIN
    :new.IDLAV:= S_ID_LAVORATORE.nextval;
END;


/
ALTER TRIGGER "ORION3G"."T_ID_LAVORATORE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_T0
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ORION3G"."TRIGGER_T0" 
 before INSERT ON LAVORATORE
 FOR EACH ROW
DECLARE
n NUMBER(20);

BEGIN

if (:new.TIPOLAV='CAPOC') THEN  
select count (*) into n from  LAVORATORE where (LAVORATORE.TIPOLAV='CAPOC') AND LAVORATORE.IDCANT=:new.IDCANT;

END IF;

if (n>0)

then 
raise_application_error(-20007, 'è possibile associare un solo capocantiere per cantiere');
rollback;


 END IF;

END;
/
ALTER TRIGGER "ORION3G"."TRIGGER_T0" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_T1
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ORION3G"."TRIGGER_T1" 
 before INSERT ON SENSORE
 FOR EACH ROW
DECLARE
n NUMBER(20);
x NUMBER(20);
Y NUMBER (20);


BEGIN

select count (*) into n from  LAVORATORE where (LAVORATORE.TIPOLAV='OPERATORE') AND LAVORATORE.IDLAV=:new.IDLAV;
select count (*) into x from  AREA where AREA.IDAREA=:NEW.IDAREA AND IDCANT=(SELECT IDCANT FROM LAVORATORE WHERE LAVORATORE.IDLAV=:NEW.IDLAV);
select count (*) into Y from SENSORE  WHERE SENSORE.IDAREA=:NEW.IDAREA OR SENSORE.IDLAV=:NEW.IDLAV;


if (n<=0)

then 
raise_application_error(-20006, 'è possibile associare sensori solo a OPERATORE');
rollback;


END IF;

if (x<=0) 
then 
raise_application_error(-20007, 'Questo lavoratore non appartiene allo stesso cantiere dell area selezionata');
rollback;

END IF;


if (Y>=2)

then 
raise_application_error(-20008, 'non è possibile aggiungere più di due sensori per area');
rollback;

END IF;


END;
/
ALTER TRIGGER "ORION3G"."TRIGGER_T1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_T3
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ORION3G"."TRIGGER_T3" 
 before INSERT ON CREDENZIALI
 FOR EACH ROW
DECLARE
n NUMBER(20);

BEGIN

select count (*) into n from  LAVORATORE where (LAVORATORE.TIPOLAV='AMMINISTRATORE' OR LAVORATORE.TIPOLAV='CAPOC') AND LAVORATORE.IDLAV=:new.IDLAV;


if (n<=0)

then 
raise_application_error(-20002, 'è possibile associare credenziali solo ad AMMINISTRATORE e CAPOCANTIERE ');
rollback;


 END IF;

END;
/
ALTER TRIGGER "ORION3G"."TRIGGER_T3" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_T4
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ORION3G"."TRIGGER_T4" 
 before INSERT ON AREA
 FOR EACH ROW
DECLARE
n NUMBER(20);

BEGIN

select count (*) into n from  LAVORATORE where (LAVORATORE.TIPOLAV='RESPONSABILE') AND LAVORATORE.IDLAV=:new.IDLAV and LAVORATORE.IDCANT=:new.IDCANT;


if (n<=0)

then 
raise_application_error(-20003, 'è possibile associare AREE SOLO AD OPERAI RESPONSABILI dello stesso cantiere dell area ');
rollback;


 END IF;
 
 
 
 
 

END;
/
ALTER TRIGGER "ORION3G"."TRIGGER_T4" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_T5
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ORION3G"."TRIGGER_T5" 
 AFTER INSERT ON LAVORATORE
 FOR EACH ROW

BEGIN


if (:new.TIPOLAV='CAPOC' OR :new.TIPOLAV='AMMINISTRATORE' ) THEN

INSERT INTO CREDENZIALI VALUES(:NEW.NOME||:NEW.COGNOME, :NEW.COGNOME||'1234', :NEW.IDLAV);

END IF;

END;


/
ALTER TRIGGER "ORION3G"."TRIGGER_T5" DISABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_T6
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ORION3G"."TRIGGER_T6" 
before INSERT ON DATISENSORE

 FOR EACH ROW



BEGIN


IF (:NEW.datorumore>50)
then

:NEW.ALLARME:=1;

END IF;

END;
/
ALTER TRIGGER "ORION3G"."TRIGGER_T6" ENABLE;
--------------------------------------------------------
--  Constraints for Table CREDENZIALI
--------------------------------------------------------

  ALTER TABLE "ORION3G"."CREDENZIALI" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "ORION3G"."CREDENZIALI" MODIFY ("IDLAV" NOT NULL ENABLE);
  ALTER TABLE "ORION3G"."CREDENZIALI" ADD CONSTRAINT "PK_CREDENZIALI" PRIMARY KEY ("UTENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ORION3G"."CREDENZIALI" ADD UNIQUE ("IDLAV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LAVORATORE
--------------------------------------------------------

  ALTER TABLE "ORION3G"."LAVORATORE" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "ORION3G"."LAVORATORE" MODIFY ("COGNOME" NOT NULL ENABLE);
  ALTER TABLE "ORION3G"."LAVORATORE" MODIFY ("DATAN" NOT NULL ENABLE);
  ALTER TABLE "ORION3G"."LAVORATORE" MODIFY ("TIPOLAV" NOT NULL ENABLE);
  ALTER TABLE "ORION3G"."LAVORATORE" ADD CONSTRAINT "C_UNO" CHECK ((TIPOLAV='AMMINISTRATORE') OR (TIPOLAV='CAPOC' OR TIPOLAV='OPERAIO SEMPLICE'  OR TIPOLAV='OPERATORE' OR TIPOLAV='RESPONSABILE') AND IDCANT IS NOT NULL) ENABLE;
  ALTER TABLE "ORION3G"."LAVORATORE" ADD CONSTRAINT "PK_LAVORATORE" PRIMARY KEY ("IDLAV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ORION3G"."LAVORATORE" ADD CONSTRAINT "LAVORATORE_UK1" UNIQUE ("NOME", "COGNOME", "DATAN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SENSORE
--------------------------------------------------------

  ALTER TABLE "ORION3G"."SENSORE" MODIFY ("IDLAV" NOT NULL ENABLE);
  ALTER TABLE "ORION3G"."SENSORE" MODIFY ("IDAREA" NOT NULL ENABLE);
  ALTER TABLE "ORION3G"."SENSORE" ADD CONSTRAINT "PK_SENSORE" PRIMARY KEY ("IDSENSORE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CANTIERE
--------------------------------------------------------

  ALTER TABLE "ORION3G"."CANTIERE" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "ORION3G"."CANTIERE" MODIFY ("DESCRIZIONE" NOT NULL ENABLE);
  ALTER TABLE "ORION3G"."CANTIERE" ADD CONSTRAINT "PK_CANTIERE" PRIMARY KEY ("IDCANTIERE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table AREA
--------------------------------------------------------

  ALTER TABLE "ORION3G"."AREA" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "ORION3G"."AREA" MODIFY ("IDLAV" NOT NULL ENABLE);
  ALTER TABLE "ORION3G"."AREA" ADD CONSTRAINT "PK_AREA" PRIMARY KEY ("IDAREA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ORION3G"."AREA" ADD UNIQUE ("IDLAV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ORION3G"."AREA" MODIFY ("IDCANT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DATISENSORE
--------------------------------------------------------

  ALTER TABLE "ORION3G"."DATISENSORE" MODIFY ("DATORUMORE" NOT NULL ENABLE);
  ALTER TABLE "ORION3G"."DATISENSORE" MODIFY ("DATOGAS" NOT NULL ENABLE);
  ALTER TABLE "ORION3G"."DATISENSORE" MODIFY ("DATAG" NOT NULL ENABLE);
  ALTER TABLE "ORION3G"."DATISENSORE" MODIFY ("IDSENS" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table AREA
--------------------------------------------------------

  ALTER TABLE "ORION3G"."AREA" ADD CONSTRAINT "FK_CANTIERE2" FOREIGN KEY ("IDCANT")
	  REFERENCES "ORION3G"."CANTIERE" ("IDCANTIERE") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ORION3G"."AREA" ADD CONSTRAINT "FK_LAVORATORE2" FOREIGN KEY ("IDLAV")
	  REFERENCES "ORION3G"."LAVORATORE" ("IDLAV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CREDENZIALI
--------------------------------------------------------

  ALTER TABLE "ORION3G"."CREDENZIALI" ADD CONSTRAINT "FK_LAVORATORE3" FOREIGN KEY ("IDLAV")
	  REFERENCES "ORION3G"."LAVORATORE" ("IDLAV") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DATISENSORE
--------------------------------------------------------

  ALTER TABLE "ORION3G"."DATISENSORE" ADD CONSTRAINT "FK_SENSORE" FOREIGN KEY ("IDSENS")
	  REFERENCES "ORION3G"."SENSORE" ("IDSENSORE") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LAVORATORE
--------------------------------------------------------

  ALTER TABLE "ORION3G"."LAVORATORE" ADD CONSTRAINT "FK_CANTIERE1" FOREIGN KEY ("IDCANT")
	  REFERENCES "ORION3G"."CANTIERE" ("IDCANTIERE") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SENSORE
--------------------------------------------------------

  ALTER TABLE "ORION3G"."SENSORE" ADD CONSTRAINT "FK_AREA" FOREIGN KEY ("IDAREA")
	  REFERENCES "ORION3G"."AREA" ("IDAREA") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ORION3G"."SENSORE" ADD CONSTRAINT "FK_LAVORATORE" FOREIGN KEY ("IDLAV")
	  REFERENCES "ORION3G"."LAVORATORE" ("IDLAV") ENABLE;
